### PR TITLE
Adding Tenniel illustrations (but currently very rough, has problems!)

### PR DESCRIPTION
**Pull request by drgrigg**
I'm not sure that a pull request is the best way to have handled this. I can back-track if necessary and do things in better chunks.

All the Tenniel illustrations are scanned to PNG and converted to SVG, and all have been inserted as figures into the text, and a LoI created. I also added a frontispiece, since all print editions of Alice have the court scene as a frontispiece.

But I've had to mess a lot with CSS to try to make things look good, as some of the originals are only half-page width, some are extremely tall, etc.

And I'm being driven nuts by some weird thing which is stopping the title page from displaying the name of the illustrator, even though that's in the titlepage.svg.

So I would review this somewhere safe, not the production version of the ebook. I'd be grateful for your comments and advice (as always!).

### CODE REVIEW

**Comment by acabal** [comment]
Just glancing at the titlepage, you added content but did not change the viewbox. Thus the illustrator is outside of the image's frame. You can run `create-draft` and pass it the illustrator flag to have it generate the right titlepage for you.

I also see that some filenames are uppercased, please lowercase all of them. I'll review the rest a little later. Thanks! :)

**Comment by drgrigg** [comment]
I wish I could learn the lesson of waiting at least one night to post up stuff. I invariably wake in the middle of the night with the solution, or with a better idea. Of course, my midnight brain said, it's the viewport, you idiot!

I've also had second thoughts about my messing with the CSS, so maybe don't review for a bit until after I commit again. But the bulk of the tedious work in getting the images in is done.

**Comment by drgrigg** [comment]
The problem with trying to do even moderately clever stuff with the CSS for images is that a lot of ereaders seem to simply ignore it (iBooks, I'm looking at you!) and you end up with a worse result than if you hadn't tried. The Kindle respects settings like float left and float right, and you get a nice result, but iBooks et.al. ignore those settings, and even seem to ignore max-width, let alone max-height.

**Comment by drgrigg** [comment]
Alex: this note here is to let you know that I'm going to close the current pull request on this project and start again once we're happy with how the illustrations are working.

Probably best to review my forked repository directly here: 
https://github.com/drgrigg/lewis-carroll_alices-adventures-in-wonderland.git

**Pull request closed without merging**
